/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TodoAppJFrame;

/**
 *
 * @author Edvaldojr
 */
public class TelaTodoApp extends javax.swing.JFrame {

    /**
     * Creates new form TelaTodoApp
     */
    public TelaTodoApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fundoVerde = new javax.swing.JPanel();
        PnlFundoBranco = new javax.swing.JPanel();
        lblSejaBemVindo = new javax.swing.JLabel();
        btnEntrar = new javax.swing.JButton();
        lblEsqueciSenha = new javax.swing.JLabel();
        txfLogin = new javax.swing.JTextField();
        txfSenha = new javax.swing.JTextField();
        lblCliqueAqui = new javax.swing.JLabel();
        lblTodoApp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        fundoVerde.setBackground(new java.awt.Color(0, 153, 102));

        PnlFundoBranco.setBackground(new java.awt.Color(255, 255, 255));

        lblSejaBemVindo.setBackground(new java.awt.Color(0, 0, 0));
        lblSejaBemVindo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSejaBemVindo.setForeground(new java.awt.Color(0, 0, 0));
        lblSejaBemVindo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSejaBemVindo.setText("Seja Bem Vindo");

        btnEntrar.setBackground(new java.awt.Color(204, 204, 204));
        btnEntrar.setForeground(new java.awt.Color(0, 0, 0));
        btnEntrar.setText("Entrar");
        btnEntrar.setBorder(null);

        lblEsqueciSenha.setForeground(new java.awt.Color(0, 0, 0));
        lblEsqueciSenha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEsqueciSenha.setText("Esqueci minha senha?");

        txfLogin.setBackground(new java.awt.Color(255, 255, 255));
        txfLogin.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Login", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        txfSenha.setBackground(new java.awt.Color(255, 255, 255));
        txfSenha.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Senha", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        javax.swing.GroupLayout PnlFundoBrancoLayout = new javax.swing.GroupLayout(PnlFundoBranco);
        PnlFundoBranco.setLayout(PnlFundoBrancoLayout);
        PnlFundoBrancoLayout.setHorizontalGroup(
            PnlFundoBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlFundoBrancoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(PnlFundoBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSejaBemVindo, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                    .addComponent(btnEntrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEsqueciSenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txfLogin)
                    .addComponent(txfSenha))
                .addGap(30, 30, 30))
        );
        PnlFundoBrancoLayout.setVerticalGroup(
            PnlFundoBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlFundoBrancoLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblSejaBemVindo)
                .addGap(28, 28, 28)
                .addComponent(txfLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(lblEsqueciSenha)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        lblCliqueAqui.setBackground(new java.awt.Color(255, 255, 255));
        lblCliqueAqui.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCliqueAqui.setForeground(new java.awt.Color(255, 255, 255));
        lblCliqueAqui.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCliqueAqui.setText("Clique aqui para cadastrar");

        lblTodoApp.setBackground(new java.awt.Color(255, 255, 255));
        lblTodoApp.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTodoApp.setForeground(new java.awt.Color(255, 255, 255));
        lblTodoApp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTodoApp.setText("Todo App");

        javax.swing.GroupLayout fundoVerdeLayout = new javax.swing.GroupLayout(fundoVerde);
        fundoVerde.setLayout(fundoVerdeLayout);
        fundoVerdeLayout.setHorizontalGroup(
            fundoVerdeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fundoVerdeLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(fundoVerdeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTodoApp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCliqueAqui, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PnlFundoBranco, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50))
        );
        fundoVerdeLayout.setVerticalGroup(
            fundoVerdeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundoVerdeLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(lblTodoApp)
                .addGap(40, 40, 40)
                .addComponent(PnlFundoBranco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(lblCliqueAqui)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fundoVerde, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fundoVerde, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaTodoApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaTodoApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaTodoApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaTodoApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaTodoApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PnlFundoBranco;
    private javax.swing.JButton btnEntrar;
    private javax.swing.JPanel fundoVerde;
    private javax.swing.JLabel lblCliqueAqui;
    private javax.swing.JLabel lblEsqueciSenha;
    private javax.swing.JLabel lblSejaBemVindo;
    private javax.swing.JLabel lblTodoApp;
    private javax.swing.JTextField txfLogin;
    private javax.swing.JTextField txfSenha;
    // End of variables declaration//GEN-END:variables
}
